version: "3.9"

services:
  api:
    build: .
    container_name: tier1-api
    ports:
      - "8080:80"
    environment:
      APP_ENV: development
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: appuser
      DB_PASSWORD: apppass
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    container_name: tier2-db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    # ports:
    #   - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: tier-redis
    ports:
      - "6379:6379"
